server_port: 50004
database_url: mariadb://1.orgvoid.top:3306/org_system
database_username: root
database_password: muzixi369
redis_url: localhost:6379
redis_username:
redis_password:
redis_expire: 3600
