server_port: 8000
database_url: mariadb://localhost:3306/org_system
database_username: root
database_password: 369
redis_url: 43.134.32.208:6379
redis_username:
redis_password: Z#2nTt98ve!Q#*RY
redis_expire: 3600
